aws_role: "arn:aws:iam::123456789012:role/CrossAccountRole"
source_database: "source_db"
destination_database: "destination_db"
query_files:  # List of SQL files to be executed
  - "./query/query1.sql"
  - "./query/qquery2.sql"
  - "./query/qquery3.sql"
athena_output_location: "s3://your-athena-query-results-bucket/"
destination_bucket: "your-destination-bucket"
file_format: "csv" # or "parquet" or "json" 